# -*- coding: utf-8 -*-
"""Assignment-26/04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUKa15VOt2wke_7VJdBbM7wTkKRPmrxj
"""

n = int(input("Enter the number of rows: "))

for i in range(1, n + 1):
    # Print leading spaces
    for j in range(n - i):
        print(" ", end=" ")
    # Print stars
    for k in range(2 * i - 1):
        print("*", end="")
    print()

n = int(input('enter required number: '))

# Upper half of the diamond (pyramid)
for i in range(1,n+1):
   for j in range(n-i):
     print(' ', end = '')
   for k in range(2*i-1):
     print('*',end = '')
   print()


for i in range(n-1, 0, -1):
    for j in range(n-i):
        print(' ', end = '')
    for k in range(2*i-1):
        print('*', end = '')
    print()