# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pq6YpGK7jPTh03QhBlWPPCMtEb_082L-
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram
from scipy.cluster.hierarchy import cut_tree

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Country-data.csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df.duplicated().sum()

# EDA Perform

df.hist(figsize=(15,12))
plt.show()

# corelaton map
plt.figure(figsize=(10,10))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

df.head()

numerical_df = df[['child_mort','exports','health','imports','income','inflation','life_expec','total_fer','gdpp']]
numerical_df.head()

numerical_df.shape

numerical_df.info()

numerical_df.describe()

numerical_df.hist(figsize=(15,12))
plt.show()

plt.figure(figsize=(10,10))
f = numerical_df
for i in enumerate(f.columns):
  plt.subplot(3,3,i[0]+1)
  sns.distplot(f[i[1]])
plt.show()

# check for outlaiers for each column
plt.figure(figsize = (20,10))
sns.boxplot(x = numerical_df.gdpp,data =numerical_df )

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.income,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.life_expec,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.total_fer,data=numerical_df)

"""no nuch outlaiers here in total_fer

"""

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.inflation,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.exports,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.imports,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.health,data=numerical_df)

plt.figure(figsize=(20,10))
sns.boxplot(x=numerical_df.child_mort,data=numerical_df)
#

# Removing staticial out liers

Q1 = df.gdpp.quantile(0.05)
Q3 = df.gdpp.quantile(0.95)
IQR = Q3-Q1
df = df[(numerical_df.gdpp <= Q3+ 1.5*IQR)]

Q1 = numerical_df.income.quantile(0.05)
Q3 = numerical_df.income.quantile(0.95)
IQR = Q3 - Q1
df = df[(numerical_df.income <= Q3 + 1.5*IQR)]


Q1 = numerical_df.life_expec.quantile(0.05)
Q3 = numerical_df.life_expec.quantile(0.95)
IQR = Q3 - Q1
df = df[(numerical_df.life_expec >= Q1 - 1.5*IQR)]

# now check grpha again for outlaiers

plt.figure(figsize=(20,5))
sns.boxplot(x=df.income,data=df)

plt.figure(figsize = (20,5))
sns.boxplot(x = df.life_expec, data =df)

# need to create numeric df again coz we removed outliers so dimensions might change

num_df = df[['child_mort', 'exports', 'health', 'imports', 'income','inflation', 'life_expec', 'total_fer', 'gdpp']]

df_corr = num_df.corr()
df_corr

plt.figure(figsize=(15,10))
sns.heatmap(df_corr, annot=True)
plt.show()

plt.figure(figsize = (20, 15))
sns.pairplot(num_df)

#Scaling

scalar = StandardScaler()

#fit transform
num_df_scaled = scalar.fit_transform(num_df)
num_df_scaled.shape

#changing scaled data into df

num_df_scaled = pd.DataFrame(num_df_scaled)
num_df_scaled.head()

#checking cluster tendency using Hopkin statistics

#Calculating the Hopkins statistic
from sklearn.neighbors import NearestNeighbors
from random import sample
from numpy.random import uniform
import numpy as np
from math import isnan

def hopkins(X):
    d = X.shape[1]
    #d = len(vars) # columns
    n = len(X) # rows
    m = int(0.1 * n)
    nbrs = NearestNeighbors(n_neighbors=1).fit(X.values)

    rand_X = sample(range(0, n, 1), m)

    ujd = []
    wjd = []
    for j in range(0, m):
        u_dist, _ = nbrs.kneighbors(uniform(np.amin(X,axis=0),np.amax(X,axis=0),d).reshape(1, -1), 2, return_distance=True)
        ujd.append(u_dist[0][1])
        w_dist, _ = nbrs.kneighbors(X.iloc[rand_X[j]].values.reshape(1, -1), 2, return_distance=True)
        wjd.append(w_dist[0][1])

    H = sum(ujd) / (sum(ujd) + sum(wjd))
    if isnan(H):
        print(ujd, wjd)
        H = 0

    return H

print(hopkins(num_df_scaled))

"""K-Means Clustering

"""

ssd = []
for k in range(2,11):
    kmean = KMeans(n_clusters = k).fit(num_df_scaled)
    ssd.append([k, kmean.inertia_])

ssd = pd.DataFrame(ssd)
plt.plot(ssd[0], ssd[1])

# silhouette analysis

range_n_clusters = [2, 3, 4, 5, 6, 7, 8]

for num_clusters in range_n_clusters:

    # intialise kmeans
    kmeans = KMeans(n_clusters=num_clusters, max_iter=50)
    kmeans.fit(num_df_scaled)

    cluster_labels = kmeans.labels_

    # silhouette score
    silhouette_avg = silhouette_score(num_df_scaled, cluster_labels)
    print("For n_clusters={0}, the silhouette score is {1}".format(num_clusters, silhouette_avg))

# silhouette analysis plots
ss = []
for k in range(2,11):
    kmeans = KMeans(n_clusters = k).fit(num_df_scaled)
    ss.append([k, silhouette_score(num_df_scaled, kmeans.labels_)])

sil = pd.DataFrame(ss)
plt.plot(sil[0],sil[1])

# final model with k=4
kmeans = KMeans(n_clusters=4, max_iter=50, random_state = 0)
kmeans.fit(num_df_scaled)

df['cluster_id'] = kmeans.labels_
df.head()

df.cluster_id.value_counts()

sns.scatterplot(x = 'gdpp', y ='child_mort', hue = 'cluster_id', data = df, palette = 'Set1')

sns.scatterplot(x = 'gdpp', y ='income', hue = 'cluster_id', data = df, palette = 'Set1')

sns.scatterplot(x = 'income', y ='child_mort', hue = 'cluster_id', data = df, palette = 'Set1')

plt.figure(figsize = (20,15))
plt.subplot(1,3,1)
sns.boxplot(x='cluster_id', y='gdpp', data= df)




plt.subplot(1,3,2)
sns.boxplot(x='cluster_id', y='income', data= df)



plt.subplot(1,3,3)
sns.boxplot(x='cluster_id', y='child_mort', data= df)

df[['gdpp', 'child_mort', 'income', 'cluster_id']].groupby('cluster_id').mean()

#Using k = 3 to do the same analysis
kmeans = KMeans(n_clusters=3, max_iter=50, random_state = 0)
kmeans.fit(num_df_scaled)

df['cluster_id'] = kmeans.labels_
df.head()

df.cluster_id.value_counts()

mean_df = df[['gdpp', 'child_mort', 'income', 'cluster_id']].groupby('cluster_id').mean()
mean_df

required_cluster = mean_df.sort_values(by = ['gdpp', 'child_mort', 'income'], ascending = [True, False, True]).head(1)
reqd = required_cluster.reset_index()
cluster = int(reqd.cluster_id)
cluster

plt.figure(figsize = (20,15))
plt.subplot(1,3,1)
sns.boxplot(x='cluster_id', y='gdpp', data= df)


plt.subplot(1,3,2)
sns.boxplot(x='cluster_id', y='income', data= df)


plt.subplot(1,3,3)
sns.boxplot(x='cluster_id', y='child_mort', data= df)

sns.scatterplot(x = 'gdpp', y ='income', hue = 'cluster_id', data = df, palette = 'Set1')

sns.scatterplot(x = 'gdpp', y ='child_mort', hue = 'cluster_id', data = df, palette = 'Set1')

sns.scatterplot(x = 'income', y ='child_mort', hue = 'cluster_id', data = df, palette = 'Set1')

c1 = df[df['cluster_id']==cluster]
c1.head()

c1.sort_values(by = ['gdpp', 'child_mort', 'income'], ascending = [True, False, True]).head(5)

#Hireracial Clustering

df.head()

df.head()

# single linkage
mergings = linkage(num_df_scaled, method="single", metric='euclidean')
dendrogram(mergings)
plt.show()

# complete linkage
mergings = linkage(num_df_scaled, method="complete", metric='euclidean')
dendrogram(mergings)
plt.show()

#cut tree model
# 3 clusters
cluster_labels_3 = cut_tree(mergings, n_clusters=3).reshape(-1, )
cluster_labels_3

df['cluster_labels_3'] = cluster_labels_3
df.head()

df.cluster_labels_3.value_counts()

cluster_labels = cut_tree(mergings, n_clusters=4).reshape(-1, )
cluster_labels

df['cluster_labels'] = cluster_labels
df.head()

df.cluster_labels.value_counts()

mean_df2 = df[['gdpp', 'child_mort', 'income', 'cluster_labels']].groupby('cluster_labels').mean()
mean_df2

mean_df2.sort_values(by = ['gdpp', 'child_mort', 'income'], ascending = [True, False, True]).head(1)

required_cluster2 = mean_df2.sort_values(by = ['gdpp', 'child_mort', 'income'], ascending = [True, False, True]).head(1)
reqd2 = required_cluster2.reset_index()
cluster2 = int(reqd2.cluster_labels)
cluster2

plt.figure(figsize = (20,15))
plt.subplot(1,3,1)
sns.boxplot(x='cluster_labels', y='gdpp', data= df)


plt.subplot(1,3,2)
sns.boxplot(x='cluster_labels', y='income', data= df)


plt.subplot(1,3,3)
sns.boxplot(x='cluster_labels', y='child_mort', data= df)

c2 = df[df['cluster_labels']==cluster2]
c2.head()

c2.sort_values(by = ['gdpp', 'child_mort', 'income'], ascending = [True, False, True]).head(5)

