# -*- coding: utf-8 -*-
"""Linear regression practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDLsug8ip7tASNYlYq8oCFZRNd1DWRcu
"""

#for warnings
import warnings
warnings.filterwarnings('ignore')

# importimg required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# reading csv file from drive
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing.csv')
df.head()

#### 1. EDA - Null Analysis, Outlier Analysis, Dropping of unnecassary columns
###  2. Univariate, multivariate -> insight generation, where exactly do we think the model can help, hypothesis of testing (which variables do we need to get maximum feature importanace)
#### 3. Feature Engineering -> Scaling, Encoding
#### 4. Testing assumptions of LR
#### 5. Build a model
#### 6. Validate it using validation set or test set
#### 7. Evaluation -> r2, Adj r2, MSE, MAE, MAPE

#Null Analysis

df.isnull().sum()

df.info()

df.describe()

sns.pairplot(df)

sns.boxplot(x = 'furnishingstatus', y = 'price', hue = 'hotwaterheating',data = df)

df['furnishingstatus'].value_counts()

categorical = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea','furnishingstatus']
binary = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

def binary_map(x):
  return x.map({'yes':1,'no':0})
df[binary] = df[binary].apply(binary_map)
df[binary].head()

df.info()

status = pd.get_dummies(df['furnishingstatus'],drop_first=True)
status.head()

status.info()

df = pd.concat([df,status], axis = 1)
df.head()

df.drop('furnishingstatus', axis = 1, inplace = True)
df.head()

# train test split

from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, train_size = 0.8, random_state = 101)
df_train.shape
df_test.shape

df_train.shape

from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()

numerical = ['area','bedrooms','bathrooms','stories','parking','price']

df_train[numerical] = scalar.fit_transform(df_train[numerical])
df_train.describe()

## heatmap to check co-relation and multi co linearity

plt.figure(figsize=(20,20))
sns.heatmap(df_train.corr(), annot = True)

y_train = df_train.pop('price')
x_train = df_train

y_train.head()

x_train.info()

x_train = x_train.apply(pd.to_numeric, errors = 'coerce')
x_train.info()

y_train = y_train.apply(pd.to_numeric, errors = 'coerce')
y_train.info()

import statsmodels.api as sm

x_train.reset_index(drop = True)
y_train.reset_index(drop = True)

x_train.info()

x_train.columns

x_train = sm.add_constant(x_train)
x_train.head()

x_train = x_train[['const', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea']]
x_train.head()

lr = sm.OLS(y_train,x_train).fit()
print(lr.summary())

from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['Features'] = x_train.columns
vif['VIF'] = [variance_inflation_factor(x_train.values, i) for i in range(x_train.shape[1])]
vif['VIF'] = round(vif['VIF'],2)
vif = vif.sort_values(by = 'VIF', ascending = False)
vif

y_train_pred = lr.predict(x_train)

sns.distplot((y_train - y_train_pred),bins=20)

df_test[numerical] = scalar.transform(df_test[numerical])
df_test.describe()

y_test = df_test.pop('price')

x_test = df_test

x_test = x_test [[ 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea']]
x_test.head()

x_test = sm.add_constant(x_test)
x_test.head()

y_test_pred = lr.predict(x_test)

sns.distplot((y_test - y_test_pred),bins = 20)

plt.scatter(y_test, y_test_pred)

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

#Root Mean Square Error
rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
rmse

r2_score(y_test, y_test_pred)

#####   SK Learn  #####

df.head()

df[['semi-furnished','unfurnished']] = df[['semi-furnished','unfurnished']].astype(int)
df.info()
df_train,df_test = train_test_split(df,train_size = 0.7, random_state = 100 )

scalar = MinMaxScaler()

numerical = ['area','bedrooms','bathrooms','stories','parking','price']

df_train[numerical] = scalar.fit_transform(df_train[numerical])

