# -*- coding: utf-8 -*-
"""LR Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlJvC_EICRn99rlh22wOhO3_21y3ncQQ
"""

import warnings
from warnings import filterwarnings

filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/day-day.csv')

df.head()

df.info()

df.describe()

"""### Data Preprocessing and Cleaning

First, let's convert the `dteday` column to a datetime object.
"""

df['dteday'] = pd.to_datetime(df['dteday'], format='%d-%m-%Y')
print(df['dteday'].dtype)

df.info()

df.shape

sns.pairplot(df)

# Drop columns that aren't useful for predicting 'cnt'
df.drop(['instant','dteday','casual','registered'], axis= 1, inplace=True)

df.isnull().sum()

df.duplicated().sum()

df['season'] = df['season'].map({1: 'spring', 2: 'summer', 3: 'fall', 4: 'winter'})
df['weathersit'] = df['weathersit'].map({1: 'clear', 2: 'misty', 3: 'light', 4: 'heavy'})
df['weekday'] = df['weekday'].astype('category')
df['mnth'] = df['mnth'].astype('category')

df.info()

dummy = pd.get_dummies(df[['season','weathersit','mnth','weekday']], drop_first=True, dtype= int)

dummy.head()

df = pd.concat([df,dummy], axis = 1)
df.head()

df.info()

df.drop(['season','mnth','weathersit','weekday'], inplace= True, axis=1)

df.head()

## train test split
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df,train_size=0.7,random_state=100)
df_train.shape

df_test.shape

#scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

numericals = ['temp','atemp','hum','windspeed']
df_train[numericals] = scaler.fit_transform(df_train[numericals])
df_train.describe()

plt.figure(figsize=(20,20))
sns.heatmap(df_train.corr(),annot=True)

y_train = df_train.pop('cnt')
x_train = df_train

y_train.head()

x_train.info()

x_train = x_train.apply(pd.to_numeric, errors='coerce')
x_train.info()

y_train = pd.to_numeric(y_train, errors='coerce')
y_train.info()

import statsmodels.api as sm

x_train.reset_index(drop=True, inplace = True)
y_train.reset_index(drop=True, inplace = True)

x_train.info()

x_train.columns

x_train = sm.add_constant(x_train)

x_train.head()

lr = sm.OLS(y_train,x_train).fit()

print(model.summary())

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif['Features'] = x_train.columns
vif['VIF'] = [variance_inflation_factor(x_train.values, i) for i in range(x_train.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

#x_train = x_train.drop('atemp', axis=1)
#x_train = x_train.drop('weekday_2', axis = 1)
# x_train = x_train.drop('weekday_1', axis = 1)
# x_train = x_train.drop('weekday_6', axis = 1)
# x_train = x_train.drop('mnth_11', axis=1)
# x_train = x_train.drop('mnth_12', axis=1)
# x_train = x_train.drop('mnth_7', axis=1)
# x_train = x_train.drop('mnth_2', axis=1)
# x_train = x_train.drop('weekday_3', axis=1)
# x_train = x_train.drop('mnth_4', axis=1)
# x_train = x_train.drop('mnth_6', axis=1)
# x_train = x_train.drop('mnth_5', axis=1)

lr = sm.OLS(y_train,x_train).fit()

print(lr.summary())

vif = pd.DataFrame()
vif['Features'] = x_train.columns
vif['VIF'] = [variance_inflation_factor(x_train.values, i) for i in range(x_train.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

y_train_predict = lr.predict(x_train)

sns.distplot((y_train - y_train_predict), bins = 20)

df_test[numericals] = scaler.transform(df_test[numericals])
df_test.head()

y_test = df_test.pop('cnt')
x_test = df_test

x_test = sm.add_constant(x_test)
x_test = x_test[x_train.columns]

x_test.head()

y_test_pred = lr.predict(x_test)

sns.distplot((y_test - y_test_pred), bins = 20)

plt.scatter(y_test, y_test_pred)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')

from sklearn.metrics import r2_score, mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
rmse

r2_score(y_test, y_test_pred)

