# -*- coding: utf-8 -*-
# """Numpy_Assignment.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1uqp1PqNW7zu2t-7u2y6aQvNWshOSd-Gw
# """

#question-1 &2
import numpy as np
np.version.version

#Question-3

X = np.arange(10)
X
# print(np.arange(10))

#question -3 create boolean array
bool_array = np.ones((3,3),dtype = bool)
print(bool_array)

#question -4 How to extract odd items that satisfy a given condition from 1D array?
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10])
array[array%2 !=0]

# Question - 5
array[array % 2 != 0] = -1
array

# Question  - 6
array = np.arange(10)
# array
new = array.copy()
new[new % 2 != 0] = -1
print(array)
print(new)
#
# new

#Question - 7 Reshape !D to 2D array

array = np.arange(10)
array
array_2d = array.reshape(2,5)
array_2d

# Question -8 vertical stack
a = np.arange(10).reshape(2,-1)
a
b = np.repeat(1,10).reshape(2,-1)
b
np.vstack((a,b))

#Question -9  horizontal stack

np.hstack((a,b))

"""# **doubt in 10**"""

# Question - 10 ###custom sequence
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]



# np.hstack((np.repeat(a, 3), np.tile(a, 3)))

# question - 11  get the common numbers
a = np.array([1,2,3,2,3,4,3,4,5,6,7])
b = np.array([7,2,10,2,7,4,9,4,9,8,3])
np.intersect1d(a,b)

#question-12 remove common item
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

# question 13 compare position
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

# question - 14 get range of items 5 - 10
a = np.array([2, 6,3,7,1,8, 1, 9, 10, 3, 27])
a[(a>5)&(a<15)]

"""# **Not at all understand this**"""

# Question 15 - Convert the function maxx that works on two scalars, to work on two arrays.
# Solution

def pair_max(x, y):
    # here I am using map to make tuple from a and b, other solution is using zip(a,b)
    maximum = [max(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    # using zip
    # maximum = [maxx(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)


# or  other solution

np.maximum(a,b)

# Question 16 Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]

# Question 17 swap 2 rows
arr = np.arange(12).reshape(3,4)
arr
arr[[1,0,2],:]

# Question 18  reverse 2D array rows

arr = np.arange(16).reshape(4,4)
arr
arr[::-1,:]

# Question 19  reverse 2d array columns

arr = np.arange(9).reshape(3,3)
arr
arr[:,::-1]

# question -20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

arr = np.random.uniform(5,10, size = (5,3))
arr

# question - 21 print upto 3 decimal places only

arr = np.random.random([5,3])
np.set_printoptions(precision=3)
arr

"""## **could't understand **"""

#question -22 Pretty print rand_arr by suppressing the scientific notation (like 1e10)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr

#question 23  Limit the number of items printed in python numpy array a to a maximum of 6 elements.

arr = np.arange(15)
np.set_printoptions(threshold = 6)
arr

# Question -24  Print the full numpy array a without truncating.
arr = np.arange(15)
arr
np.set_printoptions(threshold = 15)
arr

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
# Question - 25  How to import a dataset with numbers and texts keeping the text intact in python numpy?
iris_data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/iris.csv', delimiter=',', skip_header=1,
                          usecols = [0,1,2,3,4], dtype = object)
iris_data

## Question -26 How to extract a particular column from 1D array of tuples?

data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/iris.csv', delimiter=',', skip_header=1,
                          usecols = [-1], dtype = object)
data

# Question -27# Question: Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/iris.csv', delimiter=',', skip_header=1, dtype='float', usecols=[0,1,2,3])
iris_data

# Question: 28 Find the mean, median, standard deviation of iris's sepallength (1st column)

iris_data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/iris.csv', delimiter=',', skip_header=1, usecols = [1])

print('Mean', np.mean(iris_data))
print('Median', np.median(iris_data))
print('Standard Deviation', np.std(iris_data))

# Question: 29 Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.



(iris_data - np.min(iris_data))/(np.max(iris_data) - np.min(iris_data))

# Question: 30 Compute the softmax score of sepallength.


softmax = np.exp(iris_data)/sum(np.exp(iris_data))
softmax.sum() # it must sum 1
softmax

