# -*- coding: utf-8 -*-
# """nupmy&pandas.ipynb

# '''Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/19lvUArLMYomQuecO-kLX3jipR7pWDlaD
# '''

#question-1
import numpy as np
np.version.version

#question -2
size = 5
fixed = [0]*size
print(fixed)

zeros = np.zeros((3,3))
print(zeros)

ones = np.ones((3,3))
print(ones)

random = np.full((3,3),5)
print(random)

seq_arr = np.arange(1,16)
print(seq_arr)

line = np.linspace(0,5,10)
print(line)

#reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.size)
new_arr = arr.reshape(6,2)
print(new_arr)

new_arr = arr.reshape(2,3,2)
print(new_arr)

new = arr.reshape(3,2,2)
print(new)

array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
reshaped = array.reshape(-1)
print(reshaped)

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(array.size)
new = array.reshape(2,2,-1)
# print(new)
new2 = array.reshape(2,-1,4)
# print(new2)
new3 = array.reshape(4,-1)
# print(new3)
new4 = array.reshape(4,4)
print(new4)

#creating 1D array
array = np.array([10, 20, 30, 40, 50])

#slicing
sub_array = array[1:4]
# print(sub_array)
sub_array = array[0:6:2]
print(sub_array)
sub_array = array[::2]
print(sub_array)

#Slicing 2D Array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
arr_2d = array_2d[0:2,1:3]
print(arr_2d)

#bool array
bool_array = array > 30
print(array[bool_array])
print(array[array%10==0])

print(array)
array[0] = 100
print(array)
array[1:3] = [200,300]
print(array)

# 3d array slicing
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])
sub_array = array_3d[0,1,0:2]
print(sub_array)
subarr = array_3d[:,1,:3]
print(subarr)
subarr = array_3d[:,1,2]
print(subarr)

array_2d = np.array([[100,200,300],[400,500,600]])

combined = array_2d[1:,[0,2]]
print(combined)

array_2d[array_2d >400]=0
print(array_2d)

#Addition of matrix
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
c = np.array([3,4,5,6])
ans = np.add(a,b)
print(ans)

ans = a+b+c
print(ans)

#subtract
ans = b-a
print(ans)
ans = np.subtract(a,b)
print(ans)

#multiplication
ans = np.multiply(a,b)
print(ans)
ans = a*b
print(ans)

#division
ans = np.divide(a,b)
print(ans)
ans = a/b
print(ans)

#Mean
arr = [20, 2, 7, 1, 34]
print(np.mean(arr))

in_num1 = 10
in_num2 = 21

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out = np.minimum(in_num1, in_num2)
print(out)
out = np.maximum(in_num1, in_num2)
print(out)

# Standard Deviation
arr = [20, 2, 7, 1, 34]
print(np.std(arr, dtype = np.float64))

#reshape
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(array.size)
new_array = array.reshape(4,3)
print(new_array)

#flattening array

f_array = new_array.flatten()
print(f_array)

#Transpose
print(new_array)
transpose_array = new_array.T
print(transpose_array)

#concatinating
#along row axis = 0
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

conc_arr = np.concatenate((arr1,arr2),axis=0)
print(conc_arr)
conc_arr = np.concatenate((arr1,arr2),axis=1)
print(conc_arr)
conc_arr = np.concatenate((arr1,arr2),axis=None)
print(conc_arr)
# conc_arr = np.concatenate((arr1,arr2),axis=2)
# print(conc_arr)

#  Question: Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
new = np.vstack((a,b))
print(new)

#reverse an array
arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.flip(arr)
print(arr)

# Question: Get all items between 5 and 10 from a.

# Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a>=5) & (a<=10)])

# Find the maximum value from both of these array

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(max(a.max(),b.max()))

# a.max()
# b.max()
print()
# print(np.where (a>b),a,b)
# print(np.maximum(a,b))

"""# PANDAS"""

import pandas as pd

from re import S
a = pd.Series([1,2,3,4])
S = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print(a)
print(S)

data = {'Name' : ['Trishi','Sravanthi','Sindhu'],
        'age' : [5,35,25],
        'salary' : [5000,50000,500000]}
df = pd.DataFrame(data)
print(df)

df.shape

df.head()
df.head(1)

df.tail()
df.tail(1)

df.info()

df.describe()

df[df['age'] > 30]

df[(df['age']>30)&(df['salary']>30000)]

df[df['Name'].isin(['Trishi','Sravanthi'])]

df[df['Name'].str.contains('hi')]
df[df['Name'].str.startswith('T')]
df[df['Name'].str.endswith('i')]

df['New Salary'] = df['salary']*1.1
df

df.drop('New Salary',axis = 1, inplace  = True)
df

df.rename(columns = {'salary' : 'Annual Salary'}, inplace = True)
df

df.rename(index={0 : 'Row_0'}, inplace = True)
df

df = df.reindex([0,1,2,3,4,5])
df

df.fillna(0, inplace=True)
df

df.dropna(inplace=True)

df

df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 'age': [22, 25, 24,
28], 'occupation': ['engineer', 'doctor', 'data analyst', 'teacher']})

df

df.head()

df.columns

df.info()

df.describe()

df['age']

df.age

df[['age','name']]

df[1:3]

df[2::2]

df[0:0]

df[2:2]

df[::2]

df.iloc[2,2]

df.iloc[2,1]

df['occupation'][3]

df.iloc[3]

df.iloc[2,1:3]

df.iloc[[1,2,3]]

df.iloc[1:3,0:3]

df.loc[2,'occupation']

df.loc[3]

df.loc[:,'name':'occupation']

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/BikeIndia.csv')
df.head()

df.tail()

df.describe()

df.info()

type(df[['yr']])

df.loc[2:6,['windspeed','registered']]

df.set_index('instant', inplace = True)

df.head(10)

df.reset_index(inplace = True)

df.head()

df[0
   :1]

df2 = df[df['windspeed'] > 0][['windspeed','atemp','temp']]
df2.head()

df3 = pd.merge(df,df2 ,how='left', on=['atemp','temp'])
df3.shape

df3.head(10)

df3.info()

df4 = pd.concat([df,df2], axis=0)

df4.head()

df4.info()

df['count_2'] = df['cnt'].apply(lambda x : x * 2)
df.head()

df['surrogate'] = df['dteday'].astype('str') + ": " + df['cnt'].astype('str')
df.head()

df.describe().columns

df5 = df[['temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt']]
df5.head()

df.drop(['count_2','surrogate'], axis = 1, inplace = True)
df.head()

df5.corr()

