# -*- coding: utf-8 -*-
"""practice_loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki02kabqq3j7Um0Ra4tAGxxyvLAqj35P
"""

# Nested for loop example
for i in range(3):  # Outer loop
    for j in range(2):  # Inner loop
        print(f"i: {i}, j: {j}")

"""#Keep Multiplying Found Values by Two (Easy): Practice iterative checks and updating a value."""

inp = [1, 2, 3, 4]
num = int(input('Enter the number: '))

# As long as the number is in the list, double it
while num in inp:
    num = num * 2

print(f"The final doubled value is: {num}")

num = int(input('Enter number : '))
while num <100 :
  num = num*2
  print(f'current num is : {num}')
print(f'final value is : {num}')

m = int(input('enter number for required rows: '))
n = int(input('enter number for required columns: '))
for i in range(m):
  for j in range(n):
    print('*',end =' ')
  print()

n = 7
for i in range(1,n+1):
  for j in range(n-i+1):
    print('*',end =' ')
  print()

n = 7
for i in range(n, 0, -1):
    # Loop for spaces
    for j in range(n - i):
        print(" ", end=" ")

    # Loop for stars
    for k in range(i):
        print("*", end=" ")

    # Move to the next line
    print()

n = int(input("Enter the number of rows for the pyramid: "))

for i in range(1, n + 1):
    # Print leading spaces
    for j in range(n - i):
        print(" ", end="")
    # Print stars
    for k in range(2 * i - 1):
        print("*", end="")
    print()

n = int(input('enter required number: '))

# Upper half of the diamond (pyramid)
for i in range(1,n+1):
   for j in range(n-i):
     print(' ', end = '')
   for k in range(2*i-1):
     print('*',end = '')
   print()


for i in range(n-1, 0, -1):
    for j in range(n-i):
        print(' ', end = '')
    for k in range(2*i-1):
        print('*', end = '')
    print()